
%YAML 1.2
---
name: sample-1100_no_stop
display_name: sample-1100 no stop
engine: lc0_23
options:
  weightsPath: sample-1100_no_stop-300-150000.pb.gz
full_config:
  dataset:
    name: sample-1100
    path: /data/transfer_players_train/
  gpu: 1
  model:
    back_prop_blocks: 99
    filters: 64
    keep_weights: true
    path: maia/1900
    residual_blocks: 6
    se_ratio: 8
  training:
    batch_size: 256
    checkpoint_steps: 500
    lr_boundaries:
    - 35000
    - 80000
    - 110000
    lr_values:
    - 0.01
    - 0.001
    - 0.0001
    - 1.0e-05
    num_batch_splits: 1
    policy_loss_weight: 1.0
    precision: half
    shuffle_size: 256
    test_steps: 2000
    total_steps: 150000
    train_avg_report_steps: 50
    value_loss_weight: 1.0
...
